### ISSUE TITLE
Roadmap to v2.0

### ISSUE THREAD

**Issue by jraller** [ucdavis/wayfinding#25]
- [ ] Remove console logging - was used to easily trace and verify function paths
- [ ] Trim API - check with Chris about 
- [ ] make datastore creation into Grunt task instead of node script
- [ ] Memory reduction for datastore to optimize both disk and client memory
- [ ] Finish Zoom implementation
- [ ] Verify all callback behaviors
- [ ] Document
- [ ] Bower
- [ ] version number

Possible for 2.1 and beyond?

- [ ] Karma Jasmine testing v2.1?
- [ ] svg lint see #5 
- [ ] svg optimize for datastore versions (remove scaffolding items like portals, doors, paths - leave rooms
- one way paths

**Comment by jraller** [comment]
For the JSON minification I'm leaning toward:
{
	"paths": [[{                     // p
		"floor": "floor1",             // f
		"mapNum": 0,                   // n
		"route": 225,                  // r
		"prior": 25,                   // p
		"ax": "297",                   // x
		"ay": "273",                   // y
		"doorA": [],                   // d
		"bx": "315",                   // m
		"by": "273",                   // n
		"doorB": [],                   // e
		"length": 18,                  // l
		"connections": [25],           // c
		"portals": [1],                // q
		"priorType": "pa"              // o
	}]],
	"portals": [{                    // q
		"type": "Elev",                // t
		"accessible": true,            // a
		"idA": "Elev.1.floor2",        // e
		"floorA": "floor1",            // f
		"floorANum": 0,                // g
		"xA": "297",                   // x
		"yA": "237",                   // y
		"connectionsA": [18],          // c
		"idB": "Elev.1.floor1",        // i
		"floorB": "floor2",            // j
		"floorBNum": 1,                // k
		"xB": "297",                   // m
		"yB": "237",                   // n
		"connectionsB": [1],           // d
		"length": 50.91168824543142,   // l
		"route": 329.91168824543144,   // r
		"prior": 18,                   // p
		"priormapNum": 0,              // q
		"priorType": "pa"              // o
	}]
}

**Comment by jraller** [comment]
Heading toward pulling the zoom API calls out.

**Comment by jraller** [comment]
the console command `grunt datastore` now works.

**Comment by ironman-gampala** [comment]
Sir, Can you kindly let me know how to deploy this project either on windows10/ubuntu15.04 and how to deploy and run. what are the dependencies and required softwares/frameworks to run this way-finder?
